#!/usr/bin/env bash
# =============================================================================
# sync_env.sh
# Stamps the canonical common.env into every lab directory as labN/.env, so
# all lab stacks read identical image tags, credentials, ports, and sizing.
# This is the mechanism that keeps the labs consistent: edit common.env once,
# re-run this, and every lab moves together.
#
# It does NOT edit any lab compose file. Compose auto-reads the .env it drops.
#
# Usage:  ./sync_env.sh [REPO_ROOT]
#   REPO_ROOT defaults to ${SD411_REPO} (from common.env) or the parent of
#   vm-base if that is unset. Any directory matching lab[0-9]* gets a .env.
# =============================================================================
set -euo pipefail

log()  { printf '[sync] %s\n' "$*"; }
warn() { printf '[sync][WARN] %s\n' "$*" >&2; }
die()  { printf '[sync][FAIL] %s\n' "$*" >&2; exit 1; }

HERE="$(cd "$(dirname "$0")" && pwd)"
VM_BASE="$(cd "${HERE}/.." && pwd)"
COMMON_ENV="${VM_BASE}/common.env"
[ -f "${COMMON_ENV}" ] || die "common.env not found at ${COMMON_ENV}"

# shellcheck disable=SC1090
. "${COMMON_ENV}"

REPO_ROOT="${1:-${SD411_REPO:-$(cd "${VM_BASE}/.." && pwd)}}"
[ -d "${REPO_ROOT}" ] || die "repo root not found: ${REPO_ROOT}"
log "repo root: ${REPO_ROOT}"

STAMP_HEADER="# AUTO-GENERATED by vm-base/scripts/sync_env.sh — DO NOT EDIT.
# Source of truth is vm-base/common.env. Re-run sync_env.sh to refresh.
"

count=0
shopt -s nullglob
for dir in "${REPO_ROOT}"/lab[0-9]*; do
  [ -d "${dir}" ] || continue
  target="${dir}/.env"
  { printf '%s' "${STAMP_HEADER}"; cat "${COMMON_ENV}"; } > "${target}"
  log "stamped ${target}"
  count=$((count + 1))
done
shopt -u nullglob

if [ "${count}" -eq 0 ]; then
  warn "no lab[0-9]* directories found under ${REPO_ROOT}; nothing stamped"
  exit 2
fi
log "done — ${count} lab .env file(s) synced from common.env"
exit 0