#!/usr/bin/env python3
"""
SD411 Lab 08 - dimension builder (INSTRUCTOR PLUMBING, run once per stack)

Derives the two small dimension tables Lab 08 joins against, from the pitch
fact Lab 06 wrote. Students do not edit this file; it runs in Part 0.

    docker compose exec spark-master spark-submit \
      --master spark://spark-master:7077 \
      --jars /opt/spark/extra-jars/hadoop-aws-3.3.4.jar,/opt/spark/extra-jars/aws-java-sdk-bundle-1.12.262.jar \
      /opt/lab08/scripts/build_skew_dims.py

Writes:
    s3a://$S3_BUCKET/dim/pitch_type   ~15-19 rows   (the broadcast-sized side)
    s3a://$S3_BUCKET/dim/events       ~20-30 rows   (Part 5 stretch)

Exit codes:
    0   both dimensions written
    64  no fact table at $FACT_PREFIX (Lab 06 never ran on this stack)
    65  fact table is missing a column Lab 08 requires
"""

import os
import sys

from pyspark.sql import SparkSession, functions as F

BUCKET = os.environ.get("S3_BUCKET", "sd411")
FACT_PREFIX = os.environ.get("FACT_PREFIX", "fact/pitches")
FACT_PATH = f"s3a://{BUCKET}/{FACT_PREFIX}"
DIM_PITCH_PATH = f"s3a://{BUCKET}/dim/pitch_type"
DIM_EVENTS_PATH = f"s3a://{BUCKET}/dim/events"

REQUIRED = ["pitch_type", "events", "batter", "game_pk", "release_speed"]

# Pitch-type families. Anything Statcast emits that is not listed here lands in
# "other", so an unexpected code does not fail the build.
FAMILY = {
    "FF": ("Four-Seam Fastball", "fastball"),
    "SI": ("Sinker", "fastball"),
    "FC": ("Cutter", "fastball"),
    "FT": ("Two-Seam Fastball", "fastball"),
    "FA": ("Fastball", "fastball"),
    "SL": ("Slider", "breaking"),
    "ST": ("Sweeper", "breaking"),
    "SV": ("Slurve", "breaking"),
    "CU": ("Curveball", "breaking"),
    "KC": ("Knuckle Curve", "breaking"),
    "CS": ("Slow Curve", "breaking"),
    "CH": ("Changeup", "offspeed"),
    "FS": ("Split-Finger", "offspeed"),
    "FO": ("Forkball", "offspeed"),
    "SC": ("Screwball", "offspeed"),
    "EP": ("Eephus", "offspeed"),
    "KN": ("Knuckleball", "offspeed"),
    "PO": ("Pitchout", "other"),
}


def main():
    spark = (SparkSession.builder
             .appName("lab08-build-dims")
             .master("spark://spark-master:7077")
             .config("spark.hadoop.fs.s3a.endpoint", os.environ.get("S3_ENDPOINT", "http://minio:9000"))
             .config("spark.hadoop.fs.s3a.access.key", os.environ.get("MINIO_ROOT_USER", "sd411admin"))
             .config("spark.hadoop.fs.s3a.secret.key", os.environ.get("MINIO_ROOT_PASSWORD", "sd411password"))
             .config("spark.hadoop.fs.s3a.path.style.access", "true")
             .config("spark.hadoop.fs.s3a.connection.ssl.enabled", "false")
             .config("spark.hadoop.fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
             .getOrCreate())
    spark.sparkContext.setLogLevel("WARN")

    try:
        fact = spark.read.parquet(FACT_PATH)
    except Exception as e:  # noqa: BLE001
        print(f"FATAL: cannot read the pitch fact at {FACT_PATH}", file=sys.stderr)
        print(f"       {e}", file=sys.stderr)
        print("       Lab 06 is the writer of this table. Bring up lab06, run its",
              file=sys.stderr)
        print("       writer, then re-run this script.", file=sys.stderr)
        sys.exit(64)

    missing = [c for c in REQUIRED if c not in fact.columns]
    if missing:
        print(f"FATAL: the fact at {FACT_PATH} is missing required columns: {missing}",
              file=sys.stderr)
        print(f"       Lab 08 requires: {REQUIRED}", file=sys.stderr)
        sys.exit(65)

    # --- dim/pitch_type -----------------------------------------------------
    codes = [r["pitch_type"] for r in
             fact.select("pitch_type").distinct().collect()
             if r["pitch_type"] is not None]
    rows = []
    for c in sorted(codes):
        label, fam = FAMILY.get(c, (f"Unclassified ({c})", "other"))
        rows.append((c, label, fam))
    dim_pitch = spark.createDataFrame(rows, "pitch_type string, pitch_label string, pitch_family string")
    dim_pitch.coalesce(1).write.mode("overwrite").parquet(DIM_PITCH_PATH)
    print(f"  wrote {dim_pitch.count()} rows to {DIM_PITCH_PATH}")

    # --- dim/events ---------------------------------------------------------
    # Nulls are excluded on purpose. The whole point of Part 5.2 is that the
    # null-key rows have nothing to match, and what Catalyst does about that
    # differs between an inner join and a left outer join.
    ev = (fact.select("events").where(F.col("events").isNotNull()).distinct()
              .withColumn("is_out", F.col("events").rlike("out|strikeout|double_play|sac_"))
              .withColumn("is_hit", F.col("events").isin("single", "double", "triple", "home_run")))
    ev.coalesce(1).write.mode("overwrite").parquet(DIM_EVENTS_PATH)
    print(f"  wrote {ev.count()} rows to {DIM_EVENTS_PATH}")

    spark.stop()


if __name__ == "__main__":
    main()
